"use client";

import { useState } from "react";
import { BellRing, HardDriveUpload, LifeBuoy, Palette, Save, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";

type SettingsMap = Record<string, Record<string, unknown>>;

async function saveSetting(key: string, value: Record<string, unknown>) {
  const response = await fetch("/api/admin/settings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ key, value }) });
  const result = await response.json(); if (!response.ok) throw new Error(result.error);
}

export function SettingsForm({ initial }: { initial: Array<{ key: string; value: Record<string, unknown> }> }) {
  const map = Object.fromEntries(initial.map((item) => [item.key, item.value])) as SettingsMap;
  const [branding, setBranding] = useState({ project_name: String(map.branding?.project_name ?? "AI BUILDER"), logo_text: String(map.branding?.logo_text ?? "AB"), primary_color: String(map.branding?.primary_color ?? "#6d5dfc") });
  const [support, setSupport] = useState({ username: String(map.support?.username ?? ""), no_access_text: String(map.support?.no_access_text ?? "") });
  const [uploads, setUploads] = useState({ max_file_size_mb: Number(map.uploads?.max_file_size_mb ?? 25) });
  const [notifications, setNotifications] = useState({ enabled: Boolean(map.notifications?.enabled ?? true) });
  const [busy, setBusy] = useState<string | null>(null);
  async function save(key: string, value: Record<string, unknown>) { setBusy(key); try { await saveSetting(key, { ...map[key], ...value }); toast.success("Настройки сохранены"); } catch (error) { toast.error(error instanceof Error ? error.message : "Ошибка"); } finally { setBusy(null); } }
  return <div className="grid gap-5 xl:grid-cols-2">
    <section className="card p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#6d5dfc]/12 text-[#a89eff]"><Palette className="size-4" /></span><div><h2 className="text-sm font-semibold">Брендинг</h2><p className="mt-1 text-xs text-[var(--muted)]">Название, логотип и основной цвет</p></div></div><div className="mt-5 grid gap-4"><label className="text-xs font-semibold">Название проекта<input value={branding.project_name} onChange={(event) => setBranding({ ...branding, project_name: event.target.value })} className="focus-ring mt-2 h-11 w-full rounded-xl border border-[var(--border)] bg-black/10 px-3 text-sm" /></label><div className="grid grid-cols-[1fr_120px] gap-3"><label className="text-xs font-semibold">Текст логотипа<input value={branding.logo_text} onChange={(event) => setBranding({ ...branding, logo_text: event.target.value.slice(0, 4) })} className="focus-ring mt-2 h-11 w-full rounded-xl border border-[var(--border)] bg-black/10 px-3 text-sm" /></label><label className="text-xs font-semibold">Цвет<span className="mt-2 flex h-11 items-center gap-2 rounded-xl border border-[var(--border)] bg-black/10 px-2"><input type="color" value={branding.primary_color} onChange={(event) => setBranding({ ...branding, primary_color: event.target.value })} className="size-7 rounded border-0 bg-transparent" /><span className="text-[10px]">{branding.primary_color}</span></span></label></div><Button loading={busy === "branding"} onClick={() => void save("branding", branding)} className="justify-self-start"><Save className="size-4" /> Сохранить</Button></div></section>
    <section className="card p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#5f8cff]/12 text-[#84adff]"><LifeBuoy className="size-4" /></span><div><h2 className="text-sm font-semibold">Поддержка</h2><p className="mt-1 text-xs text-[var(--muted)]">Контакт и экран без доступа</p></div></div><div className="mt-5 grid gap-4"><label className="text-xs font-semibold">Telegram username<input value={support.username} onChange={(event) => setSupport({ ...support, username: event.target.value.replace(/^@/, "") })} placeholder="support" className="focus-ring mt-2 h-11 w-full rounded-xl border border-[var(--border)] bg-black/10 px-3 text-sm" /></label><label className="text-xs font-semibold">Текст без доступа<textarea value={support.no_access_text} onChange={(event) => setSupport({ ...support, no_access_text: event.target.value })} rows={3} className="focus-ring mt-2 w-full rounded-xl border border-[var(--border)] bg-black/10 px-3 py-2 text-sm leading-6" /></label><Button loading={busy === "support"} onClick={() => void save("support", support)} className="justify-self-start"><Save className="size-4" /> Сохранить</Button></div></section>
    <section className="card p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#69d7d0]/10 text-[#69d7d0]"><HardDriveUpload className="size-4" /></span><div><h2 className="text-sm font-semibold">Загрузки</h2><p className="mt-1 text-xs text-[var(--muted)]">Ограничения файлов домашних заданий</p></div></div><div className="mt-5 grid gap-4"><label className="text-xs font-semibold">Максимальный размер одного файла, МБ<input type="number" min={1} max={100} value={uploads.max_file_size_mb} onChange={(event) => setUploads({ max_file_size_mb: Number(event.target.value) })} className="focus-ring mt-2 h-11 w-full rounded-xl border border-[var(--border)] bg-black/10 px-3 text-sm" /></label><p className="text-xs leading-5 text-[var(--muted)]">Поддерживаются JPG, PNG, WebP, PDF, DOC, DOCX, MP4 и MOV. Ограничение дополнительно проверяется сервером.</p><Button loading={busy === "uploads"} onClick={() => void save("uploads", uploads)} className="justify-self-start"><Save className="size-4" /> Сохранить</Button></div></section>
    <section className="card p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[var(--warning)]/10 text-[var(--warning)]"><BellRing className="size-4" /></span><div><h2 className="text-sm font-semibold">Telegram-уведомления</h2><p className="mt-1 text-xs text-[var(--muted)]">Управление сообщениями бота</p></div></div><div className="mt-5"><label className="flex items-center justify-between rounded-xl border border-[var(--border)] bg-white/[.025] p-4"><span><span className="block text-sm font-semibold">Отправлять уведомления</span><span className="mt-1 block text-xs text-[var(--muted)]">Доступ, задания, проверка и завершение</span></span><input type="checkbox" checked={notifications.enabled} onChange={(event) => setNotifications({ enabled: event.target.checked })} className="size-5 accent-[#6d5dfc]" /></label><Button loading={busy === "notifications"} onClick={() => void save("notifications", notifications)} className="mt-4"><Save className="size-4" /> Сохранить</Button></div></section>
    <section className="card p-5 sm:p-6 xl:col-span-2"><div className="flex gap-3"><ShieldCheck className="mt-0.5 size-5 shrink-0 text-[var(--success)]" /><div><h2 className="text-sm font-semibold">Администраторы и секреты</h2><p className="mt-2 text-xs leading-5 text-[var(--muted)]">Первичные администраторы задаются через <code className="rounded bg-white/[.05] px-1.5 py-1">ADMIN_TELEGRAM_IDS</code>. После первого входа роль хранится в profiles и может быть изменена на странице ученика. Токен бота, service role key и session secret доступны только серверу.</p></div></div></section>
  </div>;
}
