import Link from "next/link";
import { ArrowLeft, CalendarDays, FileText, UserRound } from "lucide-react";
import { LessonAccessControl, StudentRoleControl } from "@/components/admin/student-controls";
import { StatusPill } from "@/components/ui/status-pill";
import { requireSession } from "@/lib/auth/session";
import { getAdminStudentDetail } from "@/lib/data";
import { formatDate, initials } from "@/lib/utils";

export default async function StudentDetailPage({ params }: { params: Promise<{ profileId: string }> }) {
  const { profileId } = await params; const session = await requireSession("admin"); const data = await getAdminStudentDetail(session, profileId);
  return <><Link href="/admin/students" className="focus-ring mb-6 inline-flex items-center gap-2 rounded-lg text-sm text-[var(--muted)]"><ArrowLeft className="size-4" /> Назад к ученикам</Link><section className="card p-5 sm:p-7"><div className="flex flex-col gap-5 sm:flex-row sm:items-center"><span className="grid size-16 place-items-center rounded-[20px] bg-[#6d5dfc]/15 text-lg font-bold text-[#b8b1ff]">{initials(data.profile.first_name, data.profile.last_name)}</span><div><p className="eyebrow">Профиль ученика</p><h1 className="mt-2 text-3xl font-bold">{data.profile.first_name} {data.profile.last_name}</h1><p className="mt-1 text-sm text-[var(--muted)]">{data.profile.username ? `@${data.profile.username}` : data.profile.telegram_user_id}</p></div><div className="sm:ml-auto"><StudentRoleControl profileId={data.profile.id} role={data.profile.role} /></div></div></section>
    {!data.enrollment ? <section className="card mt-5 py-14 text-center"><UserRound className="mx-auto size-7 text-[var(--muted)]" /><p className="mt-3 font-semibold">Доступ к курсу ещё не выдавался</p></section> : <><section className="mt-5 grid gap-3 md:grid-cols-3"><div className="card p-5"><CalendarDays className="size-4 text-[#a89eff]" /><p className="mt-4 text-xs text-[var(--muted)]">Доступ выдан</p><p className="mt-1 text-sm font-semibold">{formatDate(data.enrollment.access_granted_at)}</p></div><div className="card p-5"><FileText className="size-4 text-[#a89eff]" /><p className="mt-4 text-xs text-[var(--muted)]">Работ отправлено</p><p className="mt-1 text-sm font-semibold">{data.submissions.filter((item: Record<string, unknown>) => item.status !== "draft").length}</p></div><div className="card p-5"><UserRound className="size-4 text-[#a89eff]" /><p className="mt-4 text-xs text-[var(--muted)]">Последняя активность</p><p className="mt-1 text-sm font-semibold">{formatDate(data.profile.last_seen_at)}</p></div></section><section className="card mt-5 overflow-hidden"><div className="border-b border-[var(--border)] p-5"><h2 className="font-semibold">Прогресс по урокам</h2></div><div>{data.lessons.map((lesson) => <div key={lesson.id} className="flex flex-col gap-3 border-b border-[var(--border)] p-4 last:border-0 sm:flex-row sm:items-center"><span className="grid size-9 shrink-0 place-items-center rounded-xl bg-white/[.05] text-xs font-bold">{lesson.lesson_order}</span><div className="min-w-0 flex-1"><p className="text-sm font-medium">{lesson.title}</p><p className="mt-1 text-[10px] text-[var(--muted)]">{lesson.progress?.unlocked_at ? `Открыт ${formatDate(lesson.progress.unlocked_at)}` : "Нет доступа"}</p></div><StatusPill status={lesson.progress?.status ?? "locked"} /><LessonAccessControl enrollmentId={data.enrollment.id} lesson={lesson} /></div>)}</div></section><section className="mt-5"><h2 className="mb-3 font-semibold">История заданий</h2><div className="grid gap-3">{data.submissions.length ? data.submissions.map((submission: Record<string, unknown>) => { const lesson = submission.lessons as { title?: string } | null; return <article key={String(submission.id)} className="card p-5"><div className="flex flex-wrap items-center justify-between gap-2"><div><p className="text-sm font-semibold">{lesson?.title ?? "Урок"} · попытка {String(submission.attempt_number)}</p><p className="mt-1 text-xs text-[var(--muted)]">{formatDate(String(submission.created_at))}</p></div><StatusPill status={submission.status as "draft" | "submitted" | "in_review" | "revision_requested" | "approved"} /></div><p className="mt-3 line-clamp-3 whitespace-pre-wrap text-sm leading-6 text-[#c7cad3]">{String(submission.text_content ?? "")}</p></article>; }) : <div className="card py-12 text-center text-sm text-[var(--muted)]">Заданий пока нет</div>}</div></section></>}
  </>;
}
